name: Analyze Insights Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze-insights:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Noto Sans CJK Font
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk
        echo "Noto Sans CJK 폰트 설치 완료"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas matplotlib-venn

    - name: Run insights analysis
      run: |
        python insight_analysis.py
        echo "insights 폴더 파일 목록:"
        ls -R insights/ || echo "insights 폴더가 비어있습니다."

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: analysis-results
        path: insights/**
        if-no-files-found: error

    - name: Commit and Push Changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name "JuYoungJun"
        git config --global user.email "kaks162@gmail.com"
        git remote set-url origin https://JuYoungJun:${{ secrets.PAT }}@github.com/JuYoungJun/MusicTrendsAnalysis.git
        if [ -d "insights" ] && [ "$(ls -A insights)" ]; then
          git add insights/**
          git commit -m "Automated insights upload"
          git push origin HEAD:main
        else
          echo "insights 폴더가 비어있어서 커밋하지 않습니다."
