name: Analyze Insights Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze-insights:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 저장소 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Noto Sans CJK 폰트 설치
    - name: Install Noto Sans CJK Font
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk
        echo "Noto Sans CJK 폰트 설치 완료"

    # 3. Python 환경 설정
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 4. Python 의존성 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas matplotlib-venn

    # 5. 데이터 분석 및 시각화 실행
    - name: Run insights analysis
      run: |
        python insight_analysis.py

    # 6. 결과물을 아티팩트로 업로드
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: analysis-results
        path: insights/**

    # 7. 변경된 파일 커밋 및 푸시
    - name: Commit and Push Changes
      env:
        PAT: ${{ secrets.PAT }}  # Personal Access Token
      run: |
        git config --global user.name "JuYoungJun"
        git config --global user.email "kaks162@gmail.com"
        git remote set-url origin https://JuYoungJun:${{ secrets.PAT }}@github.com/JuYoungJun/MusicTrendsAnalysis.git
        git add insights/** || echo "No files to add"
        git commit -m "Automated insights analysis upload" || echo "No changes to commit"
        git push origin HEAD:main
