name: Merge Spotify Data

on:
  push:
    paths:
      - "spotify_data/**/*.csv"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pandas jinja2

      - name: Create required directories
        run: |
          mkdir -p country_data final_data

      - name: Run merge script
        run: |
          python merge_csv.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "JuYoungJun"
          git config --global user.email "kaks162@gmail.com"
          git add country_data/* final_data/*
          git commit -m "Automated merge and upload of data files"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/JuYoungJun/test135.git
          git push origin HEAD:main
