name: Merge Spotify Data

on:
  push:
    paths:
      - "spotify_data/**/*.csv"  # CSV 파일 변경 시 실행
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 의존성 설치
      - name: Install dependencies
        run: |
          pip install pandas jinja2

      # 디버깅: 환경 확인
      - name: Debug Environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "Git version:"
          git --version
          echo "Python version:"
          python --version

      # 병합 스크립트 실행
      - name: Run merge script
        run: |
          python merge_csv.py

      # GitHub 변경 사항 확인
      - name: Debug Git Changes
        run: |
          git status
          git diff --stat

      # 병합 결과를 커밋 및 푸시
      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.PAT }}  # Personal Access Token
        run: |
          git config --global user.name "JuYoungJun"
          git config --global user.email "kaks162@gmail.com"
          git remote set-url origin https://JuYoungJun:${{ secrets.PAT }}@github.com/JuYoungJun/test135.git
          git add country_data/* final_data/* || echo "No files to add"
          git commit -m "Automated merge and upload of data files" || echo "No changes to commit"
          echo "Pushing changes..."
          GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push origin HEAD:main
